In [8]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [18]:
data = pd.read_csv('Product_sales.csv')

In [19]:
data

     Age  Bought
0      1       0
1      1       0
2      1       0
3      1       0
4      1       0
..   ...     ...
462   43       0
463   60       1
464   63       1
465   50       0
466   61       1

[467 rows x 2 columns]

In [22]:
len(data[data.Bought == 0])

262

In [23]:
len(data[data.Bought ==1])

205

In [53]:
X = data.drop(['Bought'],axis=1)

In [54]:
X

     Age
0      1
1      1
2      1
3      1
4      1
..   ...
462   43
463   60
464   63
465   50
466   61

[467 rows x 1 columns]

In [55]:
y = data['Bought']

In [56]:
y

0      0
1      0
2      0
3      0
4      0
      ..
462    0
463    1
464    1
465    0
466    1
Name: Bought, Length: 467, dtype: int64

In [51]:
X

0       1
1       1
2       1
3       1
4       1
       ..
462    43
463    60
464    63
465    50
466    61
Name: Age, Length: 467, dtype: int64

In [25]:
y = data['Bought']

In [16]:
from sklearn.ensemble import AdaBoostClassifier

In [57]:
#Train the model
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2, random_state=42)

In [30]:
data.shape

(467, 2)

In [58]:
model = AdaBoostClassifier()
model.fit(X_train, y_train)

AdaBoostClassifier()

In [60]:
y_pred = model.predict(X_test)

In [62]:
from sklearn.metrics import classification_report
print(classification_report(y_pred, y_test))

              precision    recall  f1-score   support

           0       0.96      0.98      0.97        48
           1       0.98      0.96      0.97        46

    accuracy                           0.97        94
   macro avg       0.97      0.97      0.97        94
weighted avg       0.97      0.97      0.97        94

In [63]:
from sklearn.metrics import confusion_matrix

In [64]:
confusion_matrix(y_test, y_pred)

array([[47,  2],
       [ 1, 44]])